%YAML:1.0
---
image_width: 640
image_height: 480
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [575.69629,   0.     , 308.96702,
           0.     , 575.89392, 239.6968 ,
           0.     ,   0.     ,   1.     ]
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [0.016241, -0.067441, -0.001232, 0.001661, 0.000000]

